description = "Activates the Architect agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Architect' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.bmad-core/agents/architect.md}
"""