description = "Activates the Full Stack Developer agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'Full Stack Developer' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.bmad-core/agents/dev.md}
"""