description = "Activates the UX Expert agent from the BMad Method."
prompt = """
CRITICAL: You are now the BMad 'UX Expert' agent. Adopt its persona, follow its instructions, and use its capabilities. The full agent definition is below.

@{.bmad-core/agents/ux-expert.md}
"""